rvm:
  - 1.8.7
  - 2.1.10
  - 2.3.3

gemfile:
  - gemfiles/Gemfile.cucumber-1.3
  - gemfiles/Gemfile.cucumber-2.4
  - gemfiles/Gemfile.cucumber-3.0

matrix:
  exclude:
    - gemfile: gemfiles/cucumber-3.0
      rvm: 1.8.7
    - gemfile: gemfiles/cucumber-3.0
      rvm: 2.1.10
    - gemfile: gemfiles/cucumber-2.4
      rvm: 1.8.7
